version: "3.8"

services:
  host-app:
    build:
      context: ./host-app
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_REMOTE_AUTH_URL: ${NEXT_PUBLIC_REMOTE_AUTH_URL}
        NEXT_PUBLIC_REMOTE_PROFILE_URL: ${NEXT_PUBLIC_REMOTE_PROFILE_URL}
        NEXT_PUBLIC_REMOTE_USER_PREFERENCES_URL: ${NEXT_PUBLIC_REMOTE_USER_PREFERENCES_URL}
        NEXT_PUBLIC_REMOTE_CART_URL: ${NEXT_PUBLIC_REMOTE_CART_URL}
        NEXT_PUBLIC_REMOTE_PRODUCTS_URL: ${NEXT_PUBLIC_REMOTE_PRODUCTS_URL}
        NEXT_PUBLIC_REMOTE_ORDERS_URL: ${NEXT_PUBLIC_REMOTE_ORDERS_URL}
        NEXT_PUBLIC_REMOTE_PAYMENTS_URL: ${NEXT_PUBLIC_REMOTE_PAYMENTS_URL}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_REMOTE_AUTH_URL=${NEXT_PUBLIC_REMOTE_AUTH_URL}
      - NEXT_PUBLIC_REMOTE_PROFILE_URL=${NEXT_PUBLIC_REMOTE_PROFILE_URL}
      - NEXT_PUBLIC_REMOTE_USER_PREFERENCES_URL=${NEXT_PUBLIC_REMOTE_USER_PREFERENCES_URL}
      - NEXT_PUBLIC_REMOTE_CART_URL=${NEXT_PUBLIC_REMOTE_CART_URL}
      - NEXT_PUBLIC_REMOTE_PRODUCTS_URL=${NEXT_PUBLIC_REMOTE_PRODUCTS_URL}
      - NEXT_PUBLIC_REMOTE_ORDERS_URL=${NEXT_PUBLIC_REMOTE_ORDERS_URL}
      - NEXT_PUBLIC_REMOTE_PAYMENTS_URL=${NEXT_PUBLIC_REMOTE_PAYMENTS_URL}
    command: npm run start

  user-preferences-mf:
    build:
      context: ./user-preferences-mf
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - HOST_APP_URL=${HOST_APP_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    command: npm run start

  cart-mf:
    build:
      context: ./cart-mf
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - HOST_APP_URL=${HOST_APP_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    command: npm run start

  products-mf:
    build:
      context: ./products-mf
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - HOST_APP_URL=${HOST_APP_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    command: npm run start

  orders-mf:
    build:
      context: ./orders-mf
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - HOST_APP_URL=${HOST_APP_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    command: npm run start

  payments-mf:
    build:
      context: ./payments-mf
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
      - HOST_APP_URL=${HOST_APP_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    command: npm run start

  attributes-mf:
    build:
      context: ./attributes-mf
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - HOST_APP_URL=${HOST_APP_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    command: npm run start

  review-mf: # Cambio de "reviews-mf" a "review-mf"
    build:
      context: ./review-mf # Corregido el nombre del directorio
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
      - HOST_APP_URL=${HOST_APP_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    command: npm run start
